//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductType
    {
        public int ID { get; set; }
        public string ProductTypeName { get; set; }
        public Nullable<decimal> ProductTypeCoefficient { get; set; }
    }
}
